### PR TITLE
Adding in vision cone

### PR DESCRIPTION
**Pull request by EndlessEllipse**
Literally steals matt's and honker's vision cone

TODO: make the adjustment on the vision cone more responsive when you click to face another direction

### CODE REVIEW

**Comment by HeyBanditoz** [comment]
I might steal this code for Bay

**Comment by ike709** [comment]
Is this somehow not horrible performance-wise?

**Comment by EndlessEllipse** [comment]
As far as im aware there were never any performance issues in regards to it on interbay, but we'll see when it comes to it.

**Comment by mattroks101** [comment]
There were never any vision cone performance issues on InterBay with this code @ike709. I'm sure if you try hard enough you can make performance issues with it though.

**Pull request merged**
