### PR TITLE
fixes emotes

### PR DESCRIPTION
**Pull request by kachnov**

### CODE REVIEW

**Comment by MrFroztee** [comment]
No dabberino

**Comment by kachnov** [comment]
dabbing is something people do in real life unlike these bestiality emotes

**Comment by mattroks101** [comment]
Kachnov no! Dabbing killed interbay you sick fuck!

**Comment by JakeDaBoss** [comment]
Rejected, this adds nothing to the roleplaying sense.

**Comment by kachnov** [comment]
and yet you keep this furshit in the code smh

**Comment by JakeDaBoss** [comment]
I beg your pardon?

**Pull request closed without merging**
